logica/Controllers/s3Controller.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using logica.Models;

namespace logica.Controllers
{
    [Authorize]
    public class s3Controller : Controller
    {
        private repo repo = new repo();
        private logicaDb db = new logicaDb();
        public ActionResult createS3()
        {

            return PartialView("createS3");
        }

        [HttpGet]
        public ActionResult figuriSilogistice()
        {
            return PartialView("figuriSilogistice", db.s3SilogisTable.ToList());
        }
        [HttpGet]
        public ActionResult s3CModal()
        {
            return PartialView("s3CModal", db.s3Ctable.ToList());
        }

        [HttpPost]
        public JsonResult addNewSilog(s3Silogism model)
        {
            try
            {
                return Json(new { ok = true, model = repo.addNewSilog(model) });
            }
            catch
            {
                return Json(new { ok = false });
            }

            
        }

        [HttpPost]
        public JsonResult addNewS3C(s3C model)
        {
            try
            {
                return Json(new { ok = true, model = repo.addNewS3C(model) });
            }
            catch
            {
                return Json(new { ok = false });
            }


        }

        [HttpPost]
        public JsonResult createS3(s3Cerinta model)
        {

            try
            {
                return Json(new { ok = true, model = repo.addNewS3(model) });
            }
            catch
            {
                return Json(new { ok = false, });
            }
        }

    }
}

logica/Views/s3/createS3.cshtml
<h2>Modulul de creare a subiectului III</h2>

<div class="col-md-12">
    <h5>A:</h5>
    Fie urmatoarele doua moduri silogistice:
    <button type="button" class="btn glyphicon glyphicon-plus-sign" onclick="editA(1)" id="a_1s3"></button> si
    <button type="button" id="a_2s3"class="btn glyphicon glyphicon-plus-sign" onclick="editA(2)"></button> 
    <input type="hidden" value="null" id="aInput_1" />
    <input type="hidden" value="null" id="aInput_2" />
</div>
<div class="col-md-12">
    <h5>B:</h5>
    Construiti, atat un limbaj formal cat si un limbaj normal, un silogism valid, prin care sa justificati propozitia :<textarea id="b" class="form-control"></textarea>
</div>
<div class="col-md-12">
    <h5>C:</h5>
    Fie urmatorul silogism:
    <div id="C_div"></div>
    <button type="button" class="btn btn-info glyphicon glyphicon-plus-sign" onclick="cModal()"></button>
</div>
<div class="col-md-12">
    <h5>D:</h5>
    Fie următoarea definitie:<textarea class="form-control"id="d_def" placeholder="Definitia ceruta"></textarea> 
    <br />
    <input type="text" class="form-control" id="d_term" placeholder="Termenul cerut pentru definitia de la punctul b" />
</div>
<div class="col-md-12">

</div>

<div class="modal fade bs-example-modal-sm" id="AS3" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content container" id="modal-content">
            <div id="continut" class="form-horizontal">
        @Html.Action("figuriSilogistice","s3",null)
            </div>


        </div>
    </div>
</div>
<div class="modal fade bs-example-modal-sm" id="CS3" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content container" id="modal-content">
            <div id="continut" class="form-horizontal">
                @Html.Action("s3CModal","s3",null)
            </div>


        </div>
    </div>
</div>


    <script type="text/javascript">
  
    var elementAEditor = 0;
    function editA(nr) {
        $("#AS3").modal('toggle');
        elementAEditor = nr;
        var trSelList = document.getElementById('tableSilog').getElementsByClassName('selected');
        for (var i = 0; i < trSelList.length; i++) {

            trSelList[i].classList.remove('selected');
        }

    }

    function cModal() {
        $('#CS3').modal('toggle');

    }

    </script>

logica/Views/s3/figuriSilogistice.cshtml
@model List<logica.Models.s3Silogism>

<table id="tableSilog" style="min-width:100%">
    <thead>
        <tr>
            <th>
                <button type="button" onclick="addNewSilog()" class="btn glyphicon glyphicon-plus"></button>
            </th>
          

            <th>
                <select id="maj"class="form-control-static">
                    <option value="a">a</option>
                    <option value="e">e</option>
                    <option value="i">i</option>
                    <option value="o">o</option>
                </select>
            </th>
            <th>
                <select id="min" class="form-control-static">
                    <option value="a">a</option>
                    <option value="e">e</option>
                    <option value="i">i</option>
                    <option value="o">o</option>
                </select>
            </th>

            <th>
                <select id="con"class="form-control-static">
                    <option value="a">a</option>
                    <option value="e">e</option>
                    <option value="i">i</option>
                    <option value="o">o</option>
                </select>
            </th>
            
            <th>
                <select id="fig"class="form-control-static">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                </select>
            </th>
          
        </tr>
        <tr>
            <th>ID</th>
            <th>Silogismul</th>
            <th>Figura</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody id="tableSilBody">
        @for (int i = 0; i < Model.Count(); i++)
        {
            <tr onclick="selectSilog(this)">
                <td>@Model[i].ID</td>
                <td>@Model[i].maj@Model[i].maj@Model[i].con</td>
                <td>@Model[i].fig</td>
                <td></td>
                <td></td>
            </tr>

        }
    </tbody>
</table>
<script type="text/javascript">


    function addNewSilog() {
        $.ajax({
            async: false,
            cache: false,
            type: "POST",
            url: "/s3/addNewSilog",
            data: {
                "model.maj": document.getElementById('maj').value,
                "model.min": document.getElementById('min').value,
                "model.con": document.getElementById('con').value,
                "model.fig": document.getElementById('fig').value,
            },
        }).done(function (data) {
            if (data.ok == true) {
                var string = '<tr onclick="selectSilog(this)">'
                    + '<td>' + data.model.ID + '</td>'
                + '<td>' + data.model.maj+data.model.min+data.model.con + '</td>'
                + '<td>' + data.model.fig + '</td>'
                '</tr>';
                $("#tableSilBody").prepend(string);

                ;
            } else {
                alert("Eroare la Adaugare!")
            }
        });
       
    }
    function selectSilog(el)
    {

        //element editor is the variable from the main document and it is used as an index for label of A
        if (!el.classList.contains('selected')) {
            document.getElementById('a_' + elementAEditor+'s3').innerHTML = el.getElementsByTagName('td')[1].innerHTML + '-' + el.getElementsByTagName('td')[2].innerHTML;
            document.getElementById('aInput_' + elementAEditor).value = el.getElementsByTagName('td')[0].innerHTML;
            el.classList.add('selected');
        }
        else
        {

            el.classList.remove('selected');
            document.getElementById('a_' + elementAEditor).innerHTML = '';
        }
    }
</script>

logica/Views/s3/s3CModal.cshtml
@model List<logica.Models.s3C>



<table id="tableC" style="min-width:100%">
    <thead>
        <tr>
            <th>
                <button type="button" onclick="addNewC()" class="btn glyphicon glyphicon-plus"></button>
            </th>


            <th>
               <textarea id="silogC" class="form-control" placeholder="Silogismul"></textarea>
            </th>
            <th>
                <input type="text" class="form-control" id="termC" placeholder="termenul mediu" />
            </th>

            <th><textarea class="form-control"id="premMinC" placeholder="Premisa minora a silogismului"></textarea>
            </th>

            
        </tr>
        <tr>
            <th>ID</th>
            <th>Silogismul</th>
            <th>Termenul mediu</th>
            <th>Premisa minora</th>
          
        </tr>
    </thead>
    <tbody id="tableCBody">
        @for (int i = 0; i < Model.Count(); i++)
        {
            <tr onclick="selectC(this)">
                <td>@Model[i].ID</td>
                <td>@Model[i].silog</td>
                <td>@Model[i].tMediu</td>
                <td>@Model[i].pMin</td>
          
            </tr>

        }
    </tbody>
</table>
<script type="text/javascript">


    function addNewC() {
        $.ajax({
            async: false,
            cache: false,
            type: "POST",
            url: "/s3/addNewS3C",
            data: {
                "model.silog": document.getElementById('silogC').value,
                "model.tMediu": document.getElementById('termC').value,
                "model.pMin": document.getElementById('premMinC').value,
            },
        }).done(function (data) {
            if (data.ok == true) {
                var string = '<tr onclick="selectC(this)">'
                    + '<td>' + data.model.ID + '</td>'
                + '<td>' + data.model.silog+ '</td>'
                + '<td>' + data.model.tMediu + '</td>' 
                 + '<td>' + data.model.pMin + '</td>' +
                '</tr>';
                $("#tableCBody").prepend(string);

                ;
            } else {
                alert("Eroare la Adaugare!")
            }
        });

    }
    function selectC(el)
    {

        //element editor is the variable from the main document and it is used as an index for label of A
        var trSelList2 = document.getElementById('tableCBody').getElementsByClassName('selected');
        for (var i = 0; i < trSelList2.length; i++) {

            trSelList2[i].classList.remove('selected');
        }

        if (!el.classList.contains('selected')) {

              el.classList.add('selected');
              document.getElementById('C_div').innerHTML = el.getElementsByTagName('td')[1].innerHTML +
                  '<input type="hidden"value="' + el.getElementsByTagName('td')[0].innerHTML + '" id="c_id"/>';
        }
        else
        {

            el.classList.remove('selected');

        }
    }
</script>