logica/Controllers/s1_aController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using logica.Models;
using System.IO;
using System.Xml.Serialization;
using System.Xml;
using Microsoft.AspNet.Identity;
namespace logica.Controllers
{
    [Authorize]
    public class s1_aController : Controller
    {
        // GET: s1_a
        logicaDb db = new logicaDb();
        repo repository = new repo();
        // [Route("blitz/new")]
        public ActionResult Index()
        {
            return View(db.s1Table.ToList());
        }
        [HttpPost]
        public JsonResult adaugaCerinta(List<int> idList, string nume)
        {
            try
            {
                s1_a_deschise model = new s1_a_deschise();
                model.xml_subiect = obtain_xml(idList);
                model.nume = nume;
                model.createDate = DateTime.Now;
                repository.adauga_s1VarDeschise(model);
                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(false + " ex:" + ex.ToString());
            }
        }

        public object getXml(string xml)
        {

            //   var xml = db.variantsTable.Find(id).xml;
            StringReader strReader = null;
            XmlSerializer serializer = null;
            XmlTextReader xmlReader = null;
            object obj = null;
            try
            {
                strReader = new StringReader(xml);
                serializer = new XmlSerializer(typeof(List<int>));
                xmlReader = new XmlTextReader(strReader);
                obj = serializer.Deserialize(xmlReader);
            }
            catch
            {
                //Handle Exception Code
            }
            finally
            {
                if (xmlReader != null)
                {
                    xmlReader.Close();
                }
                if (strReader != null)
                {
                    strReader.Close();
                }
            }

            return obj;
        }

        private string obtain_xml(object model)
        {
            StringWriter sw = new StringWriter();
            XmlTextWriter tw = null;
            try
            {
                XmlSerializer serializer = new XmlSerializer(model.GetType());
                tw = new XmlTextWriter(sw);
                serializer.Serialize(tw, model);
            }
            catch (Exception ex)
            {
                throw new Exception("NU s-a putut serializa xml " + model.ToString());
            }
            finally
            {
                sw.Close();
                if (tw != null)
                {
                    tw.Close();
                }


            }
            return sw.ToString();
        }
        [HttpGet]
        public ActionResult rezolvaSesiuneBlitz(int sesId)
        {
            var model = db.varianteDeschise_s1_table.Find(sesId);
            if (model.indisponibil == true && User.IsInRole("elev") == true)
            {
                return RedirectToAction("Index");
            }
            var caras = getXml(model.xml_subiect) as List<int>;
            List<s1Cerinta> listaCerinte = new List<s1Cerinta>();
            foreach (var item in caras)
            {
                s1Cerinta mod = new s1Cerinta();
                mod = repository.obtine_s1Cerinta_dupaId(item);
                listaCerinte.Add(mod);
            }
            ViewBag.sesID = sesId;
            return View(listaCerinte);
        }
        [HttpPost]
        public JsonResult rezolvaSesiuneBlitz(string punctaj, int varId, List<int> listaRaspunsuri)
        {
            try
            {
                s1_a_rezultateElev model = new s1_a_rezultateElev();
                model.idElev = User.Identity.GetUserName();
                model.idVarianta = varId;
                model.ultimulPunctaj = punctaj;
                model.dataOra = DateTime.Now;
                model.xml_listaRaspunsuri = obtain_xml(listaRaspunsuri);
                db.varianteDeschise_s1_rezultate.Add(model);
                db.SaveChanges();
                return Json(new { ok = true });
            }
            catch
            {
                return Json(new { ok = false });
            }
        }


        [HttpGet]
        public ActionResult varianteBlitzDisponibile()
        {
            if (User.IsInRole("elev"))
            {
                var model = (from m in db.varianteDeschise_s1_table
                             where m.indisponibil == false
                             select m).ToList();
                return View(model);
            }
            else
            {
                return View(db.varianteDeschise_s1_table.ToList());
            }
        }
        [HttpGet]
        public JsonResult seteazaStareVarianta(int id)
        {
            try
            {
                var model = db.varianteDeschise_s1_table.Find(id);
                if (model.indisponibil == true)
                {
                    model.indisponibil = false;

                }
                else
                {
                    model.indisponibil = true;
                }
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return Json(new { ok = true, status = model.indisponibil }, JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult varianteBlitzRezolvate()
        {
            string nume = User.Identity.GetUserName();
            var model = (from m in db.varianteDeschise_s1_rezultate
                         where m.idElev == nume && m.inactiv == false
                         select m).ToList();
            return PartialView("varianteBlitzRezolvate", model);
        }
        public JsonResult seteazaStareRezultat(int ID)
        {
            try
            {
                s1_a_rezultateElev model = db.varianteDeschise_s1_rezultate.Find(ID);

                model.inactiv = true;
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;

                db.SaveChanges();
                return Json(true);
            }
            catch
            {
                return Json(false);
            }
        }
        public ActionResult vizualizareSesiuneBlitz(int sesId, int id)
        {

            var model = db.varianteDeschise_s1_table.Find(sesId);
            if (model.indisponibil == true && User.IsInRole("elev") == true)
            {
                return RedirectToAction("varianteBlitzDisponibile");
            }
            var caras = getXml(model.xml_subiect) as List<int>;
            List<s1Cerinta> listaCerinte = new List<s1Cerinta>();
            foreach (var item in caras)
            {
                s1Cerinta mod = new s1Cerinta();
                mod = repository.obtine_s1Cerinta_dupaId(item);
                listaCerinte.Add(mod);
            }
            var rezultate = (from m in db.varianteDeschise_s1_rezultate
                             where m.ID == id
                             select m).FirstOrDefault();
            ViewBag.rezultate = rezultate;
            ViewBag.listaRaspunsuriXML = getXml(rezultate.xml_listaRaspunsuri);
            ViewBag.dataOra = rezultate.dataOra;
            return View(listaCerinte);
        }
        public ActionResult denumireVarianta_partial(int id)
        {
            try
            {
                var nume = (from m in db.varianteDeschise_s1_table
                            where m.ID == id
                            select m).FirstOrDefault();
                ViewBag.nume = nume.nume;
                return PartialView("denumireVarianta_partial");

            }
            catch
            {
                return PartialView("denumireVarianta_partial", id);
            }
        }

    }
}

logica/Views/s1_a/Index.cshtml
@model IEnumerable<logica.Models.s1Cerinta>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista cerinte Subiectul I A</h2>
<header class="container">
    <div class="row">
        <div class="col-xs-3">
            <input type="text" id="denumire" placeholder="Denumirea variantei blitz" class="form-control"/>
        </div>
        <div class="col-xs-3"><button type="button" onclick="saveSession()" class="btn glyphicon glyphicon-save">Salveaza sesiunea blitz</button></div>
    </div>
</header>
<table class="table" id="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>
                Categoria
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cerinta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.r1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.r2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.r3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.r4)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.answer)
            </th>

        </tr>
    </thead>
    <tbody id="tbody">
        @foreach (var item in Model)
        {
            <tr onclick="selectTr(this)">
                <td>@item.ID</td>
                <td>
                    @Html.DisplayFor(modelItem => item.nume)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cerinta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.r1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.r2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.r3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.r4)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.answer)
                </td>

            </tr>
        }
    </tbody>

</table>

<script  type="text/javascript">
    function selectTr(el) {
        if (el.style.backgroundColor == "bisque") {
            el.style.backgroundColor = "";
        }
        else
        {
            el.style.backgroundColor = "bisque";
        }
    }

    function saveSession()
    {
       
        var idList = [];
        var table = document.getElementById('tbody').getElementsByTagName('tr');
        
        for (var i = 0; i < table.length; i++) {

            if (table[i].style.backgroundColor == "bisque") {
                idList.push(table[i].getElementsByTagName('td')[0].innerText)
            }
        }
       
        $.ajax({
            async: false,
            cache: false,
            type: "POST",
            url: "/s1_a/adaugaCerinta",
            data: { "idList": idList,'nume':document.getElementById('denumire').value },
        }).done(function (data) {
            if (data == true) {
                alert("Adaugarea s-a efectuat cu succes!");


            } else {
                alert("Eroare la adaugare!")
            }
        });

    }
</script>

logica/Views/s1_a/denumireVarianta_partial.cshtml
@ViewBag.nume

logica/Views/s1_a/rezolvaSesiuneBlitz.cshtml
@model List<logica.Models.s1Cerinta>
@{
    ViewBag.Title = "rezolvaSesiuneBlitz";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>rezolvaSesiuneBlitz</h2>
<form action="javascript:solve(@ViewBag.sesID);">
    @for (int i = 0; i < Model.Count(); i++)
    {
        <div class="col-md-12 answers">
            <div class="row">
                @(i + 1). @Model[i].cerinta
            </div>
            <div class="row">
                <input type="radio" name="optradio_@i" value="@Model[i].answer" order="1" required>     a) @Model[i].r1
            </div>
            <div class="row">
                <input type="radio" name="optradio_@i" value="@Model.[i].answer" order="2" required>      b) @Model[i].r2
            </div>
            <div class="row">
                <input type="radio" name="optradio_@i" value="@Model[i].answer" order="3" required>       c) @Model[i].r3
            </div>
            <div class="row">
                <input type="radio" name="optradio_@i" value="@Model[i].answer" order="4" required>      d) @Model[i].r4
            </div>
        </div> <br />

    }
    <p id="punctaj"></p>
    <input type="hidden" value="@ViewBag.sesID" id="sesid" />
    <button class="btn btn-success glyphicon glyphicon-ok-sign" type="submit" onclick="" id="okBtn">Vezi rezultatul!</button>
</form>
@using (Html.BeginForm("varianteBlitzDisponibile", "s1_a", FormMethod.Get))
{


<button class="btn glyphicon glyphicon-ok-sign" type="submit" id="returnBtn" style="display:none">Intoarce-te la pagina cu variante</button>
}
<script type="text/javascript">
    function solve(sesId) {
   var list = document.getElementsByClassName('answers');
        var punctajFinal = 0;
        for (var i = 0; i < list.length; i++) {

            var el = document.getElementsByName('optradio_' + i);
          
            if (el[el[0].value - 1].checked == true) {
                //  console.log(el[el[0].value-1]);
                el[el[0].value - 1].parentNode.style.backgroundColor = 'yellowgreen';
                punctajFinal += 1;
            }
            else {

                el[el[0].value - 1].parentNode.style.backgroundColor = 'green';
                if (el[0].checked == true) {
                    el[0].parentNode.style.backgroundColor = "red";
                }
                if (el[1].checked == true) {
                    el[1].parentNode.style.backgroundColor = "red";
                }
                if (el[2].checked == true) {
                    el[2].parentNode.style.backgroundColor = "red";
                }
                if (el[3].checked == true) {
                    el[3].parentNode.style.backgroundColor = "red";
                }
            }
        }
        document.getElementById('punctaj').innerText = "Ati obtinut un punctaj final de " + punctajFinal + "puncte din " + list.length+" puncte posibile.";
        document.getElementById('okBtn').style.display = 'none';
        document.getElementById('returnBtn').style.display = 'initial';
       
        var listaRaspunsuri=[];
        for (var i = 0; i < list.length; i++) {
            var el = document.getElementsByName('optradio_' + i);
            if(el[0].checked==true){
                listaRaspunsuri.push(el[0].getAttribute('order'));
            }
            if(el[1].checked==true){
                listaRaspunsuri.push(el[1].getAttribute('order'));
            }
            if(el[2].checked==true){
                listaRaspunsuri.push(el[2].getAttribute('order'));
            }
            if(el[3].checked==true){
                listaRaspunsuri.push(el[3].getAttribute('order'));
            }
            

        }
      //  console.log(listaRaspunsuri);
        $.ajax({
            async: false,
            cache: false,
            type: "POST",
            url: "/s1_a/rezolvaSesiuneBlitz",
            data: {
                'varId': sesId,
                'punctaj':punctajFinal,
                'listaRaspunsuri':listaRaspunsuri
            },
        }).done(function (data) {
            if (data.ok == true) {
            
            }
            else {
                    alert("Eroare la salvare!")
                }
            });
    }
</script>

logica/Views/s1_a/varianteBlitzDisponibile.cshtml
@model List<logica.Models.s1_a_deschise>
@{
    ViewBag.Title = "varianteBlitzDisponibile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Variantele disponibile SI</h2>
<div class="row">
    <div class="col-md-12">
        <table>
            <thead>
                <tr>
                    <th>
                        Nume varianta
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @for (int i = 0; i < Model.Count; i++)
            {
                    <tr>
                        <td>@Model[i].nume</td>


                        <td><a class="btn btn-success glyphicon glyphicon-globe" href="/s1_a/rezolvaSesiuneBlitz?sesId=@Model[i].ID">Incepe</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-12">
        <h3>Istoricul variantelor rezolvate</h3>
    </div>
    <div class="col-md-12">
        <table>
            <thead>
                <tr>
                    <th>Numele variantei</th>
                    <th>
                        Punctaj
                    </th>
                    <th>
                        Data/ora rezolvare
                    </th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @Html.Action("varianteBlitzRezolvate")
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    function changeStatus(id,el)
    {
        $.ajax({
            async: false,
            cache: false,
            type: "GET",
            url: "/s1_a/seteazaStareVarianta",
            data: {'id':id
            },
        }).done(function (data) {
            if (data.ok == true) {
                if(data.status==true){
                    el.parentNode.style.backgroundColor='red';
                }
                else{
                    el.parentNode.style.backgroundColor='yellowgreen';
                }
                alert("Schimbarea s-a efectuat cu succes!"+data.status)
            } else {
                alert("Eroare la salvare!")
            }
        });
        
    }
    
</script>

logica/Views/s1_a/varianteBlitzRezolvate.cshtml
@model List<logica.Models.s1_a_rezultateElev>



@foreach (var item in Model)
{
    <tr>
        <td>@Html.Action("denumireVarianta_partial","s1_a", new { id=item.idVarianta})</td>
        <td>
            @item.ultimulPunctaj
        </td>
        <td>
            @item.dataOra
        </td>
        <td><a class="btn btn-success glyphicon glyphicon-search" href="/s1_a/vizualizareSesiuneBlitz?sesId=@item.idVarianta&id=@item.ID">Vizualizare raspunsuri</a></td>
        <td>
            <button type="button" class="btn btn-danger glyphicon glyphicon-remove" onclick="removeRezultatVarianta('@item.ID',this)">Sterge</button>
        </td>
    </tr>

}
<script type="text/javascript">
    function removeRezultatVarianta(id,el) {
        $.ajax({
            async: false,
            cache: false,
            type: "POST",
            url: "/s1_a/seteazaStareRezultat",
            data: {
                'id': id
            },
        }).done(function (data) {
            if (data == true) {
                    el.parentNode.parentNode.remove();
            } else {
            }
        });
    }
</script>

logica/Views/s1_a/vizualizareSesiuneBlitz.cshtml
@model List<logica.Models.s1Cerinta>
@{
    ViewBag.Title = "Vizualizare sesiune blitz";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Vizualizare sesiune blitz pentru elevul <span id="numeElev"></span></h2>
<h3>Punctaj final:<span id="punctaj"></span></h3>
<h3>Data: <span id="data"></span></h3>

@for (int i = 0; i < Model.Count(); i++)
{
    <div class="col-md-12 answers">
        <div class="row">
            @(i + 1). @Model[i].cerinta
        </div>
        <div class="row">
            <input type="radio" name="optradio_@i" value="@Model[i].answer" order="1" disabled>     a) @Model[i].r1
        </div>
        <div class="row">
            <input type="radio" name="optradio_@i" value="@Model[i].answer" order="2" disabled>      b) @Model[i].r2
        </div>
        <div class="row">
            <input type="radio" name="optradio_@i" value="@Model[i].answer" order="3" disabled>       c) @Model[i].r3
        </div>
        <div class="row">
            <input type="radio" name="optradio_@i" value="@Model[i].answer" order="4" disabled>      d) @Model[i].r4
        </div>
    </div> <br />

}
<p id="punctaj"></p>

@using (Html.BeginForm("varianteBlitzDisponibile", "s1_a", FormMethod.Get))
{


    <button class="btn btn-success glyphicon glyphicon-ok-sign" type="submit">Intoarce-te la pagina cu variante</button>
}
<script type="text/javascript">
    var listaRaspunsuri=@Html.Raw(Json.Encode(ViewBag.listaRaspunsuriXML));

    var rezultate=@Html.Raw(Json.Encode(ViewBag.rezultate));
    document.getElementById('numeElev').innerText=rezultate.idElev;
    var da=@Html.Raw(Json.Encode(ViewBag.dataOra.ToString()));
    document.getElementById('data').innerText=da;
    document.getElementById('punctaj').innerText=rezultate.ultimulPunctaj;
    //    console.log(rezultate);
    //console.log(listaRaspunsuri);
    var list = document.getElementsByClassName('answers');


    for (var i = 0; i < list.length; i++) {
        var opt1=document.getElementsByName('optradio_'+i);

        opt1[listaRaspunsuri[i]-1].checked=true;
    }
        for (var i = 0; i < list.length; i++) {

            var el=document.getElementsByName('optradio_'+i);
            if(el[el[0].value-1].checked==true){
                //  console.log(el[el[0].value-1]);
                el[el[0].value-1].parentNode.style.backgroundColor='yellowgreen';
            }
            else{

                el[el[0].value-1].parentNode.style.backgroundColor='green';
                if(el[0].checked==true){
                    el[0].parentNode.style.backgroundColor="red";
                }
                if(el[1].checked==true){
                    el[1].parentNode.style.backgroundColor="red";
                }
                if(el[2].checked==true){
                    el[2].parentNode.style.backgroundColor="red";
                }
                if(el[3].checked==true){
                    el[3].parentNode.style.backgroundColor="red";
                }
            }
        }

</script>