logica/Controllers/s1CerinteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using logica.Models;
namespace logica.Controllers
{
    [Authorize]
    public class s1CerinteController : Controller
    {
        private logicaDb db = new logicaDb();
        private repo repository = new repo();

        public ActionResult s1Index()
        {


            return View(db.s1Table.ToList());
        }

        [HttpPost]
        public JsonResult addS1(s1Cerinta model)
        {
            try
            {

                return Json(new { ok = true, model = repository.addS1Cerinta(model) });
            }
            catch
            {
                return Json(new { ok = false });
            }


        }

        [HttpGet]
        public ActionResult s1AddModal()
        {
            return PartialView("s1AddModal");
        }

        [HttpGet]
        public ActionResult variantaNoua()
        {

            return PartialView("variantaNoua", db.s1Table.ToList());
        }


        [HttpPost]
        public JsonResult variantaNoua(List<int> cerinte, int s1B)
        {
            try
            {

                return Json(new { ok = true, s1model = repository.addNewVarS1(cerinte, s1B) });
            }
            catch
            {
                return Json(new { ok = false });
            }
        }
        [HttpGet]
        public ActionResult listaVariante()
        {

            return View(db.s1VarianteTable.ToList());
        }
        [HttpGet]
        public ActionResult variantaModal(int id)
        {

            return PartialView("variantaModal", repository.getS1GrilaByID(id));
        }

        [HttpPost]
        public JsonResult deleteVar(int id)
        {
            try
            {
                repository.removeVar(id);
            }
            catch
            {

                return Json(new { ok = false });

            }

            return Json(new { ok = true });
        }

        [HttpGet]
        public ActionResult s1bPartial()
        {

            return PartialView("s1bPartial", db.s1BcerinteTable.ToList());
        }

        [HttpGet]
        public ActionResult s1BAddModal()
        {
            return PartialView("s1BAddModal");
        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult addS1B(s1B model, s1B_1 svg)
        {
            try
            {

                return Json(new { ok = true, model = repository.addS1BCerinta(model, svg) });
            }
            catch
            {
                return Json(new { ok = false });
            }


        }
        [HttpPost]
        public JsonResult deleteS1Cerinta(int id)
        {
            try
            {
                repository.removeS1Cerinta(id);
            }
            catch
            {

                return Json(new { ok = false });

            }

            return Json(new { ok = true });
        }
        [HttpPost]
        public JsonResult deleteS1BCerinta(int id)
        {
            try
            {
                repository.removeS1BCerinta(id);
            }
            catch
            {

                return Json(new { ok = false });

            }

            return Json(new { ok = true });
        }
        [HttpGet]
        public ActionResult b1()
        {

            return PartialView("b1");
        }

        [HttpGet]
        public JsonResult s1b1Modal(int id)
        {
            var model = repository.getS1B1ById(id);
            var svg = "";
            switch (model.corect)
            {
                case 1:
                    svg = model.svgObj1;
                    break;

                case 2:
                    svg = model.svgObj2;
                    break;

                case 3:
                    svg = model.svgObj3;
                    break;

                case 4:
                    svg = model.svgObj4;
                    break;
            }

            return Json(new { svg = svg }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult cerintaEditor(int id)
        {
            try
            {
                return PartialView("cerintaEditor",repository.obtine_s1Cerinta_dupaId(id));
            }
            catch
            {
                ViewBag.error = "Nu s-a putut obtine editorul pentru ceritna";
                return PartialView("cerintaEditor");
            }
        }

    }
}

logica/Views/s1Cerinte/b1.cshtml
<canvas class="col-md-4" id="canvas">

</canvas>
<script src="~/Scripts/js/fabric.js"></script>
<script  type="text/javascript">
    function add() {
        var circle = new fabric.Circle({
             radius: 50,
            stroke: 'black',
            strokeWidth: 1,
            fill: 'rgba(0,0,0,0)',
            originX: 'center',
            originY: 'center'
        });

        var textA = new fabric.Text('A', {
            fontSize: 30,
            originX: 'center',
            originY: 'center'
        });
        var textB = new fabric.Text('B', {
            fontSize: 30,
            originX: 'center',
            originY: 'center'
        });
        var textC = new fabric.Text('C', {
            fontSize: 30,
            originX: 'center',
            originY: 'center'
        });
        var textD = new fabric.Text('D', {
            fontSize: 30,
            originX: 'center',
            originY: 'center'
            });
        var group1 = new fabric.Group([circle, textA], {
            left: 150,
            top: 50,
        });

        var group2 = new fabric.Group([circle, textB], {
            left: 100,
            top: 50,
        });
        var group3 = new fabric.Group([circle, textC], {
            left: 50,
            top: 50,
        });
        var group4 = new fabric.Group([circle, textD], {
            left: 0,
            top: 50,
        });

        canvas.add(group1, group2, group3,group4);
        
       

    }

    var $ = function (id) { return document.getElementById(id) };

    var canvas = this.__canvas = new fabric.Canvas('canvas');
    //var canvas = this.__canvas = new fabric.Canvas('canvasModal');

   
    fabric.Object.prototype.transparentCorners = true;
    add();
</script>

logica/Views/s1Cerinte/cerintaEditor.cshtml
@model logica.Models.s1Cerinta

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editarea cerintei</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            <label class="control-label col-md-2">    Categoria</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nume, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nume, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Cerinta</label>
           <div class="col-md-10">
                <input class="form-control text-box single-line" id="nume" name="nume" value="caras" type="text">
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.r1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.r1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.r1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.r2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.r2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.r2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.r3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.r3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.r3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.r4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.r4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.r4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.answer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

logica/Views/s1Cerinte/listaVariante.cshtml
 @model List<logica.Models.varianta>
@{
    ViewBag.Title = "listaVariante";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>listaVariante</h2>

<table>
    <thead>
        <tr>
    @Html.ActionLink("Adauga varianta noua", "variantaNoua",null, new { @class = "glyphicon glyphicon-zoom-in btn btn-info" })            
        </tr>
        <tr>
            <th>
                ID
            </th>
            <th>
                Numele variantei
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @for (int i = 0; i < Model.Count(); i++)
    {<tr>
     <td>
         @Model[i].ID
     </td>
           <td>
               @Model[i].nume
           </td>
    <td>
        <button class="glyphicon glyphicon-zoom-in btn" type="button" onclick="openCompleteSub(@Model[i].ID)" ></button>
    </td>
        <td>
            @Html.ActionLink("Incepe testarea","testare","evaluare",new {id=Model[i].ID }, new { @class = " btn btn-success glyphicon glyphicon-blackboard" })

        </td>
        <td>
<button type="button" class="glyphicon glyphicon-remove btn btn-danger" onclick="deleteVar(@Model[i].ID,this)">

</button>
        </td>
     </tr>

    }

    </tbody>
</table>
<div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content container" id="modal-content">
            <div id="continut" class="form-horizontal">

            </div>


        </div>
    </div>
</div>
<script type="text/javascript">
    function openCompleteSub(id) 
    {
        
        $.ajax({
            async: false,
            cache: false,
            type: "GET",
            url: "/s1Cerinte/variantaModal",
            data: { "id":id },
        }).done(function (data) {
            document.getElementById('continut').innerHTML=data;
            $('#myModal').modal('show');
        });

    }
    function deleteVar(id,el){

        $.ajax({
            async: false,
            cache: false,
            type: "POST",
            url: "/s1Cerinte/deleteVar",
            data: { "id":id },
        }).done(function (data) {
            if(data.ok==true){
                el.parentNode.parentNode.remove();


            } else 
            {
                alert("Eroare la stergere!")
            }
        });

    }

</script>

logica/Views/s1Cerinte/s1AddModal.cshtml
<div class="row">
    <form action="javascript:addNewS1Cerinta()">
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label col-md-2" for="s1Name">Categoria cerintei</label>
                <div class="col-md-10">
                    <input id="s1Name" class="form-control" placeholder="Categoria">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="s1Name">Cerinta</label>

                <div class="col-md-10">
                    <textarea id="s1Cerinta" class="form-control col-md-12" placeholder="Cerinta" required></textarea>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="s1Name">Prima varianta de raspuns</label>

                <div class="col-md-10">
                    <textarea id="r1" class="form-control col-md-12" placeholder="Prima varianta de raspuns" required></textarea>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="s1Name">A doua varianta de raspuns</label>

                <div class="col-md-10">
                    <textarea id="r2" class="form-control col-md-12" placeholder="A doua varianta de raspuns" required></textarea>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="s1Name">A treia varianta de raspuns</label>

                <div class="col-md-10">
                    <textarea id="r3" class="form-control col-md-12" placeholder="A treia varianta de raspuns" required></textarea>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="s1Name">A patra varianta de raspuns</label>

                <div class="col-md-10">
                    <textarea id="r4" class="form-control col-md-12" placeholder="A patra varianta de raspuns" required></textarea>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="s1Name">Raspunsul corect</label>

                <div class="col-md-10">
                    <select class="form-control" id="s1Answer" required>
                        <option></option>
                        <option value="1">a)</option>
                        <option value="2">b)</option>
                        <option value="3">c)</option>
                        <option value="4">d)</option>

                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-12 btn-toolbar" role="toolbar">
            <button type="submit" class="btn btn-success btn-lg pull-left glyphicon glyphicon-floppy-save">Salveaza</button>
            <button type="button" onclick='$("#myModal").modal("toggle");clearInputs(document.getElementById("myModal"))' class="btn btn-danger btn-lg glyphicon glyphicon-erase pull-right">Anuleaza</button>
        </div>
    </form>

        </div>

<script type="text/javascript">
    $(document).ready(function () {
        clearInputs(document.getElementById('myModal'));
    })
    function clearInputs(element)
    {
        var lista = element.getElementsByTagName('input');
        for (var i = 0; i < lista.length; i++) {
            lista[i].value = "";
        }
        var lista = element.getElementsByTagName('textarea');
        for (var i = 0; i < lista.length; i++) {
            lista[i].value = "";
        }
         lista = element.getElementsByTagName('select');
        for (var i = 0; i < lista.length; i++) {
            lista[i].value ="";
        }

    }
    function addNewS1Cerinta() {

        $.ajax({
            async: false,
            cache: false,
            type: "POST",
            url: "/s1Cerinte/addS1",
            data: {
                "model.nume": document.getElementById("s1Name").value,
                "model.cerinta": document.getElementById("s1Cerinta").value,
                "model.r1": document.getElementById("r1").value,
                "model.r2": document.getElementById("r2").value,
                "model.r3": document.getElementById("r3").value,
                "model.r4": document.getElementById("r4").value,
                "model.answer": $("#s1Answer option:selected").val()
            },
        }).done(function (data) {
            if (data.ok == true) {
                //   location.reload(true);
                // s1ATbody

                $("#myModal").modal('toggle');
                var string = "<tr onclick=" + 'selectS1A(3,this)' + ">" +
                    "<td>" + data.model.ID + "</td>" +
                    "<td>" + data.model.nume + "</td>" +
                    "<td>" + data.model.cerinta + "</td>" +
                    "<td>" + data.model.r1 + "</td>" +
                    "<td>" + data.model.r2 + "</td>" +
                    "<td>" + data.model.r3 + "</td>" +
                    "<td>" + data.model.r4 + "</td>" +
                    "<td>" + data.model.answer + "</td>" +
                    "</tr>";
                $("#s1ATbody").prepend(string);
                clearInputs(document.getElementById('myModal'));
            }
            else {
                alert("Eroare la adaugare!")
            }
        });


    }


</script>

logica/Views/s1Cerinte/s1Index.cshtml
@model List<logica.Models.s1Cerinta>
@{
    ViewBag.Title = "s1Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<h2>s1Index</h2>
<div class="col-md-12">
    <table style="text-align:center" id="tab1">
        <thead>
            <tr>
                <th>
                    <button type="button" onclick="$('#myModal').modal('show')" style="left:2cm" class="btn glyphicon glyphicon-plus">
                        Adauga subiect A
                    </button>

                </th>
                <th>
                    <button type="button" onclick="$('#myModal2').modal('show')" style="left:2cm" class="btn glyphicon glyphicon-plus">
                        Adauga subiect B
                    </button>
                </th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            <tr>
                <th>ID</th>
                <th>Nume</th>
                <th>Cerinta</th>
                <th>R1</th>
                <th>R2</th>
                <th>R3</th>
                <th>R4</th>
                <th>Corect</th>
                <th></th>
            </tr>

        </thead>
        <tbody id="s1ATbody">
            @for (int i = 0; i < Model.Count(); i++)
        {
                <tr>
                    <td>
                        @Model[i].ID
                    </td>

                    <td>
                        @Model[i].nume
                    </td>

                    <td>
                        @Model[i].cerinta
                    </td>

                    <td>
                        @Model[i].r1
                    </td>

                    <td>
                        @Model[i].r2
                    </td>

                    <td>
                        @Model[i].r3
                    </td>

                    <td>
                        @Model[i].r4
                    </td>
                    <td>
                        @Model[i].answer
                    </td>
                    <td>
                        <button type="button" class="btn btn-success btn-sm glyphicon glyphicon-edit" onclick="editeazaCeritna(@Model[i].ID)">Editeaza cerinta</button>
                        <button type="button" class="glyphicon glyphicon-remove-circle btn btn-danger" onclick="removeS1(@Model[i].ID,this)"></button>
                    </td>
                </tr>
        }



        </tbody>
    </table>
</div>
<div class="col-md-12">
    @Html.Action("s1bPartial")
</div>

<div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content container" id="modal-content">
            <div id="continut" class="form-horizontal">

                @Html.Action("s1AddModal", "s1Cerinte")

            </div>


        </div>
    </div>
</div>
<div class="modal fade bs-example-modal-sm" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content container" id="modal-content">
            <div id="continut" class="form-horizontal">

                @Html.Action("s1BAddModal", "s1Cerinte")

            </div>


        </div>
    </div>
</div>
<div class="modal fade bs-example-modal-sm" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
    <div class="modal-dialog modal-sm" style="width:50%" role="document">
        <div class="modal-content container" id="modal-content">
            <div id="continut3" class="form-horizontal">
      
    <canvas id="canvasModal" class="col-md-12"></canvas>

              

            </div>


        </div>
    </div>
</div>
<div class="modal fade bs-example-modal-sm" id="cerintaModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content container" id="modal-content">
            <div id="modCont" class="form-horizontal">

            </div>
        </div>
    </div>
</div>

@section Scripts{

    <link href="~/Content/DataTables/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/DataTables/css/buttons.dataTables.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>

    <script src="~/Scripts/DataTables/buttons.colVis.min.js"></script>

<script type="text/javascript"> 
 //   $("#tab1").dataTable();
    // $("#tab2").dataTable();
    $(document).ready(function(){
    var canvas5 = this.__canvas = new fabric.Canvas('canvasModal');

    })
    function removeS1(id, el) {

        $.ajax({
            async: false,
            cache: false,
            type: "POST",
            url: "/s1Cerinte/deleteS1Cerinta",
            data: { "id": id },
        }).done(function (data) {
            if (data.ok == true) {
                el.parentNode.parentNode.remove();


            } else {
                alert("Eroare la stergere!")
            }
        });



    }
    function removeS1B(id, el) {

        $.ajax({
            async: false,
            cache: false,
            type: "POST",
            url: "/s1Cerinte/deleteS1BCerinta",
            data: { "id": id },
        }).done(function (data) {
            if (data.ok == true) {
                el.parentNode.parentNode.remove();


            } else {
                alert("Eroare la stergere!")
            }
        });



    }

    function editeazaCeritna(id) {

        $.ajax({
            async: false,
            cache: false,
            type: "GET",
            url: "/s1Cerinte/cerintaEditor",
            data: { "id": id },
        }).done(function (data) {
            document.getElementById('modCont').innerHTML = data;
            $('#cerintaModal').modal('show');
        });



    }
    function openDiagramModal(id) {
        $.ajax({
            async: false,
            cache: false,
            type: "GET",
            url: "/s1Cerinte/s1b1Modal",
            data: { "id": id },
        }).done(function (data) {
            if (data.svg != null) {
                canvas5.loadFromDatalessJSON(data.svg);
                $("#myModal3").modal("show");
            } else {
                alert("Eroare la cautare!")
            }
        });

    }
</script>
}

logica/Views/s1Cerinte/s1bPartial.cshtml
@model List<logica.Models.s1B>


<table id="tab2">
    <thead>
        <tr>
<th>
    ID
</th>
            <th>
                Cerinta
            </th>
        
            <th>Diagrama corecta</th>
         
            <th>
                r1
            </th>         
            <th>
                r2
            </th> 
            <th>
                r3
            </th> 
            <th>
                r4
            </th> 
            <th>
                r5
            </th> 
            <th>
                r6
            </th>
            <th></th>
                      
                </tr>
    </thead>
    <tbody id="tbodyS1B">
        @for (int i = 0; i < Model.Count(); i++)
        {
            <tr onclick="setS1BID(@Model[i].ID,this)">
                <td>
                    @Model[i].ID
                </td>
                <td>
                    @Model[i].cerinta
                </td>
              
                <td>
                    <button type="button" class="btn glyphicon glyphicon-zoom-in"onclick="openDiagramModal(@Model[i].svgId)" ></button>
                </td>
           
                <td>
                    @Model[i].r1
                    <section style="color:blue">@Model[i].answer_r1</section>
                </td>
                <td>
                    @Model[i].r2
                    <section style="color:blue">@Model[i].answer_r2</section>
                </td>
                <td>
                    @Model[i].r3
                    <section style="color:blue">@Model[i].answer_r3</section>
                </td>
                <td>
                    @Model[i].r4
                    <section style="color:blue">@Model[i].answer_r4</section>
                </td>
                <td>
                    @Model[i].r5
                    <section style="color:blue">@Model[i].answer_r5</section>
                </td>
                <td>
                    @Model[i].r6
                    <section style="color:blue">@Model[i].answer_r6</section>
                </td>
                <td>
                    <button type="button" class="btn glyphicon glyphicon-remove-circle btn btn-danger" onclick="removeS1B(@Model[i].ID,this)"></button>
                </td>
            </tr>

        }
    </tbody>
</table>

logica/Views/s1Cerinte/variantaModal.cshtml
@model logica.Models.s1GrilaViewModel
<div>
    <label class="label-success">
        @Model.var.nume
    </label>
    <table>
        <thead>
          
            <tr>
                <th>ID</th>
                <th>Nume</th>
                <th>Cerinta</th>
                <th>R1</th>
                <th>R2</th>
                <th>R3</th>
                <th>R4</th>
                <th>Corect</th>
            </tr>

        </thead>
        <tbody>
            @for (int i = 0; i < Model.cerinte.Count(); i++)
            {
                <tr>
                    <td>
                        @Model.cerinte[i].ID
                    </td>

                    <td>
                        @Model.cerinte[i].nume
                    </td>

                    <td>
                        @Model.cerinte[i].cerinta
                    </td>

                    <td>
                        @Model.cerinte[i].r1
                    </td>

                    <td>
                        @Model.cerinte[i].r2
                    </td>

                    <td>
                        @Model.cerinte[i].r3
                    </td>

                    <td>
                        @Model.cerinte[i].r4
                    </td>
                    <td>
                        @Model.cerinte[i].answer
                    </td>

                </tr>
            }



        </tbody>
    </table>
</div>

logica/Views/s1Cerinte/variantaNoua.cshtml
@model List<logica.Models.s1Cerinta>

<div id="tabdiv" class="col-md-12">
    <h1>Subiectul 1 A</h1>

    <table id="tab1">
        <thead>
            <tr>
                <th>
                    <button type="button" onclick="$('#myModals1').modal('show')" style="left:2cm" class="btn glyphicon glyphicon-plus">
                        Adauga subiect A
                    </button>

                </th>
                <th>
                    <button type="button" onclick="$('#myModal2').modal('show')" style="left:2cm" class="btn glyphicon glyphicon-plus">
                        Adauga subiect B
                    </button>
                </th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            <tr>
                <th>ID</th>
                <th>Nume</th>
                <th>Cerinta</th>
                <th>R1</th>
                <th>R2</th>
                <th>R3</th>
                <th>R4</th>
                <th>Corect</th>
            </tr>

        </thead>
        <tbody id="s1ATbody">
            @for (int i = 0; i < Model.Count(); i++)
            {
                <tr onclick="selectS1A(@Model[i].ID,this)">
                    <td>
                        @Model[i].ID
                    </td>

                    <td>
                        @Model[i].nume
                    </td>

                    <td>
                        @Model[i].cerinta
                    </td>

                    <td>
                        @Model[i].r1
                    </td>

                    <td>
                        @Model[i].r2
                    </td>

                    <td>
                        @Model[i].r3
                    </td>

                    <td>
                        @Model[i].r4
                    </td>
                    <td>
                        @Model[i].answer
                    </td>

                </tr>
            }



        </tbody>
    </table>
</div>

<div class="col-md-12">


    <table>
        <thead>
            <tr>
                <th>
                Lista cu cerinte
                </th>
                
            </tr>
            <tr>
                <th>ID</th>
                <th>Nume</th>
                <th>Cerinta</th>
                <th>R1</th>
                <th>R2</th>
                <th>R3</th>
                <th>R4</th>
                <th>Corect</th>
            </tr>

        </thead>
        <tbody id="listBody">         



        </tbody>
    </table>

</div>
<div class="col-md-12">
<h2>S1 B</h2>

    @Html.Action("s1bPartial")

</div>